version: "3"
services:
  datascience-notebook:
    build: jupyter
    container_name: datascience-notebook-container
    command: bash -c "jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' --ip 0.0.0.0 --port 8888 --allow-root"
    ports:
      - 8888:8888
